from .vpc import VpcStack
from .aurora_mysql import AuroraMysqlStack
from .kds import KinesisDataStreamStack
from .dms_iam_roles import DmsIAMRolesStack
from .dms_aurora_mysql_to_kinesis import DMSAuroraMysqlToKinesisStack
from .glue_job_role import GlueJobRoleStack
from .glue_stream_data_schema import GlueStreamDataSchemaStack
from .glue_streaming_job import GlueStreamingJobStack
from .lakeformation_permissions import DataLakePermissionsStack
from .s3 import S3BucketStack
from .bastion_host import BastionHostEC2InstanceStack
